---
- name: Copy /etc/netdata configuration files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/netdata/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart netdata service
  become: true
  loop: "{{ netdata_configuration_files }}"

- name: Copy cloud.conf configuration file
  template:
    src: cloud.conf.j2
    dest: /var/lib/netdata/cloud.d/cloud.conf
    owner: netdata
    group: netdata
    mode: 0644
  notify: Restart netdata service
  become: true

- name: Retrieve /etc/netdata/.opt-out-from-anonymous-statistics status
  stat:
    path: /etc/netdata/.opt-out-from-anonymous-statistics
  register: result

- name: Opt out from anonymous statistics
  file:
    path: /etc/netdata/.opt-out-from-anonymous-statistics
    owner: root
    group: root
    mode: 0644
    state: touch
  become: true
  when: result.stat.exists is defined and not result.stat.exists

- name: Add netdata user to docker group
  user:
    name: netdata
    groups: docker
    append: yes
  become: true
